# Generated by Django 5.1.3 on 2024-11-13 13:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('players', models.CharField(choices=[('1', '1+'), ('2', '2+'), ('3', '3+'), ('4', '4+')], max_length=10)),
                ('game_time', models.CharField(choices=[('15-30', '15-30 minutes'), ('30-60', '30-60 minutes'), ('60+', '60+ minutes')], max_length=50)),
                ('game_image_main', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('game_image_2', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image')),
                ('game_image_3', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image')),
                ('game_image_4', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image')),
                ('game_image_5', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
