# Generated by Django 5.1.3 on 2024-11-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
