# Generated by Django 5.1.3 on 2024-11-13 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_brief',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
