# Generated by Django 5.1.3 on 2024-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0003_game_game_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.CharField(choices=[('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], max_length=10),
        ),
    ]
