# Generated by Django 5.1.3 on 2024-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0005_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
