# Generated by Django 5.1.3 on 2024-11-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0006_remove_game_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-game_title']},
        ),
    ]
