# Generated by Django 5.1.3 on 2024-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0007_alter_game_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
