# Generated by Django 5.1.3 on 2024-11-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_games', '0008_alter_game_options_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
