# Generated by Django 5.1.3 on 2024-11-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
