# Generated by Django 5.1.3 on 2024-11-23 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_contact', '0002_contact_message_read_contact_message_replied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='UserContact',
        ),
    ]
