# Generated by Django 5.1.3 on 2024-11-23 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssg_contact', '0003_rename_contact_usercontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContact',
            new_name='UserMessage',
        ),
    ]
